### ISSUE TITLE
The field stabilizationWindowSeconds in HPA does to follow the regular schedule

### ISSUE THREAD

**Issue by hui-maker** [kubernetes/enhancements#2645]
Enhancement Description:

Per my understanding the field `stabilizationWindowSeconds` in HPA, indicates the amount of time the HPA controller should consider previous recommendations to prevent flapping of the number of replicas.  For example: If I set `stabilizationWindowSeconds: 300` for Pod scaling down under behavior section, it indicates the HPA controller will holding at latest 5 mins later for pod scaling down if picked the largest recommendation value above the target.
But I observed that the pod will scaling down does not follow the time specifications in `stabilizationWindowSeconds: 300`. It will not waiting at latest 5 mins for pod scaling down, but will scaling down pod about 1 min around later, once current value above the target. 

The shown below is part of HPA settings
```
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60         
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
```
