### ISSUE TITLE
Volumes to allow content merge - projected volumes

### ISSUE THREAD

**Issue by cdenneen** [kubernetes/enhancements#3237]
### Enhancement Description
Allow a projected volume to merge contents of multiple sources into a resulting key/file.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: container-test
    image: busybox
    args:
    - sleep
    - infinity
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: my-secret
      - configMap:
          name: my-config

```
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  config: |-
    SITE_URL=https://devsite.rnd.local/
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
stringData:
  secret: |-
    SUPER_SECRET=passw0rd
```

I've tried to set both to the same key and `subPath: .env` but the later is the only one that gets mounted due to key duplication I would guess:

```yaml
  .env: |-
    CONTENTS
```

would like the resulting mounted file look like:

```
> cat /projected-volume/.env
SITE_URL=https://devsite.rnd.local/
SUPER_SECRET=passw0rd
```

Not sure if that should be a projected volume parameter, volume parameter, volumeMount parameter.
